version: '3'

services:
  edge_node:
    build:
      context: .
      dockerfile: edge_node/Dockerfile.dev
    environment:
      - MINISTREAM_CONFIG=configs/jetson_orin_nano/config.yaml
      - USE_MOCK_HAL=true
    networks:
      - ministream-network

  network_api:
    build:
      context: .
      dockerfile: network_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ministream-network

  gui:
    build:
      context: .
      dockerfile: gui/Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime-root:/tmp/runtime-root
    network_mode: host

  ministream-gui:
    build:
      context: ./ministream-gui
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container's port 80 to host's port 3000
    depends_on:
      - network_api  # Assuming your API service is named 'network_api'
    environment:
      - REACT_APP_API_URL=http://localhost:8000 

networks:
  ministream-network:
    driver: bridge
