version: '3'

services:
  edge_node:
    build:
      context: .
      dockerfile: edge_node/Dockerfile.dev
    environment:
      - MINISTREAM_CONFIG=configs/jetson_orin_nano/config.yaml
      - USE_MOCK_HAL=true
    networks:
      - ministream-network

  network_api:
    build:
      context: .
      dockerfile: network_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ministream-network

  # Comment out the GUI service for now
  # gui:
  #   build:
  #     context: .
  #     dockerfile: gui/Dockerfile
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   network_mode: host

networks:
  ministream-network:
    driver: bridge
