version: '3.8'

services:
  edge_node:
    build:
      context: .
      dockerfile: edge_node/Dockerfile.dev
    environment:
      - DEVICE_ID=unique_device_id_here
      - API_URL=http://network_api:8000  # Use the service name as the hostname
      - MINISTREAM_CONFIG=configs/jetson_orin_nano/config.yaml
      - USE_MOCK_HAL=true
    networks:
      - ministream-network

  network_api:
    build:
      context: .
      dockerfile: network_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ministream-network

  ministream-gui:
    build:
      context: .
      dockerfile: ministream-gui/Dockerfile
    ports:
      - "3000:80"  # Map container's port 80 to host's port 3000
    depends_on:
      - network_api  # Assuming your API service is named 'network_api'
    environment:
      - REACT_APP_API_URL=http://network_api:8000 
    networks:
      - ministream-network

networks:
  ministream-network:
    driver: bridge
