name: Ministream CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
        component: [edge_node, network_api, gui, shared, root]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/test.txt
        pip install -r requirements/ci.txt
        if [ -f ${{ matrix.component }}/requirements.txt ]; then pip install -r ${{ matrix.component }}/requirements.txt; fi

    - name: List installed packages
      run: pip list

    - name: Lint with flake8
      run: |
        if [ "${{ matrix.component }}" != "root" ]; then
          # stop the build if there are Python syntax errors or undefined names
          flake8 ${{ matrix.component }} --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 ${{ matrix.component }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        else
          # For root, lint all Python files in the project
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        fi

    - name: Run tests with pytest and generate coverage
      run: |
        if [ "${{ matrix.component }}" == "root" ]; then
          pytest --cov=. --cov-report=xml:coverage.xml -v  # Save coverage.xml in root
        elif [ -d "${{ matrix.component }}/tests" ]; then
          pytest ${{ matrix.component }}/tests --cov=${{ matrix.component }}/src --cov-report=xml:${{ matrix.component }}/coverage.xml -v
        else
          echo "No tests directory for ${{ matrix.component }}"
          echo '<?xml version="1.0" ?><coverage version="5.5.0"><sources><source>'${{ matrix.component }}'</source></sources></coverage>' > ${{ matrix.component }}/coverage.xml
        fi
        
        echo "After running tests, contents of current directory:"
        ls -la
        
        if [ -f coverage.xml ]; then
          echo "coverage.xml file found in root. Contents:"
          cat coverage.xml
        elif [ -f ${{ matrix.component }}/coverage.xml ]; then
          echo "coverage.xml file found in ${{ matrix.component }}. Contents:"
          cat ${{ matrix.component }}/coverage.xml
        else
          echo "coverage.xml file not found!"
          echo "Creating a dummy coverage file for ${{ matrix.component }}"
          mkdir -p ${{ matrix.component }}
          echo '<?xml version="1.0" ?><coverage version="5.5.0"><sources><source>'${{ matrix.component }}'</source></sources></coverage>' > ${{ matrix.component }}/coverage.xml
        fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{ matrix.component == 'root' && './coverage.xml' || format('{0}/coverage.xml', matrix.component) }}
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Debug coverage file
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Contents of ${{ matrix.component }} directory:"
        ls -la ${{ matrix.component }} || echo "${{ matrix.component }} directory not found"
        if [ -f ${{ matrix.component }}/coverage.xml ]; then
          echo "coverage.xml file found in ${{ matrix.component }}. Contents:"
          cat ${{ matrix.component }}/coverage.xml
        elif [ -f coverage.xml ]; then
          echo "coverage.xml file found in root. Contents:"
          cat coverage.xml
        else
          echo "coverage.xml file not found!"
        fi

    - name: Check for coverage file
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Searching for coverage.xml:"
        find . -name coverage.xml

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        component: [edge_node, network_api]

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t edgeneurostream-${{ matrix.component }}:${{ github.sha }} ${{ matrix.component }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/edgeneurostream-${{ matrix.component }}:${{ github.sha }}
